version: "3.8"

services:
  app:
    build: ./app
    container_name: app_service
    ports:
      - "8045:8045"
    networks:
      - cache_network
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - cache_network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - cache_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  cache_network:
    driver: bridge
